version: '3.2'

services:
  db:
    image: postgres:13.9
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go-example-db
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2565:2565"
    env_file:
      - .env
    depends_on:
      - db
    restart: "on-failure"
    
  
 
    
    
